# Generated by Django 4.2.5 on 2023-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_alter_tiposexames_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposexames',
            name='horario_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tiposexames',
            name='horario_inicial',
            field=models.TimeField(),
        ),
    ]
